# Generated by Django 3.2.7 on 2021-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KlimovCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категорія')),
                ('desc', models.TextField(blank=True, verbose_name='Опис категорії')),
                ('professions', models.TextField(blank=True, verbose_name='Професії')),
            ],
            options={
                'verbose_name': 'Категорія професії',
                'verbose_name_plural': 'Категорії професій',
            },
        ),
        migrations.CreateModel(
            name='QuestionsBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='Запитання')),
                ('answer_1', models.TextField(blank=True, verbose_name='Відповідь 1')),
                ('answer_2', models.TextField(blank=True, verbose_name='Відповідь 2')),
                ('result_id_1', models.PositiveSmallIntegerField(null=True, verbose_name='Індекс відповіді 1')),
                ('result_id_2', models.PositiveSmallIntegerField(null=True, verbose_name='Індекс відповіді 2')),
            ],
            options={
                'verbose_name': 'Запитання',
                'verbose_name_plural': 'Запитання',
            },
        ),
    ]
