# Generated by Django 3.2.7 on 2021-12-13 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questioning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectionklimovcatstudyfield',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questioning.klimovcategory'),
        ),
        migrations.AddField(
            model_name='connectionklimovcatstudyfield',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universearch.studyfield'),
        ),
        migrations.AddField(
            model_name='connectioninterestcatspec',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questioning.interestcategory'),
        ),
        migrations.AddField(
            model_name='connectioninterestcatspec',
            name='spec_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universearch.speciality'),
        ),
    ]
