# Generated by Django 3.2.7 on 2021-12-13 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='назва')),
                ('type', models.IntegerField(choices=[(0, 'гуртожиток'), (1, 'готель'), (2, 'орендована квартира'), (3, 'хостел')], default=0, verbose_name='тип')),
                ('address', models.CharField(default='', max_length=50, verbose_name='адреса')),
                ('phone', models.CharField(default='', max_length=13, verbose_name='телефон')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='universearch.city', verbose_name='місто')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to='universearch.university', verbose_name='ВУЗ')),
            ],
            options={
                'verbose_name': 'житло',
                'verbose_name_plural': 'житла',
            },
        ),
    ]
